Atualização do PrimeFaces e melhoria na adição de novos cursos
tacianosilva/sigest pull request #31
Opened 2018-11-01 14:26 UTC by joaoeudes7

- Utilizei o componente Dialog como forma de melhoria ao adicionar um novo curso :v:

2018-11-13 19:39 UTC, tacianosilva requested changes

2018-11-13 19:39 UTC, tacianosilva commented on src/main/webapp/curso/manter.xhtml
> +=======
Porque o h:body termina aqui se ainda tem mais código para a listagem? Tem que rever esse código.

2018-11-13 19:39 UTC, tacianosilva commented on src/main/webapp/curso/manter.xhtml
> +    <hr />
A partir desta linha começa a parte de listar os cursos cadastrados. Tem um trecho repetido. Veja que o dialog deveria estar logo acima desta linha.

2018-11-16 21:09 UTC, joaoeudes7 commented
Não entendi o que houve aqui, tinha mandado minhas alterações antes e estavam tudo ok e depois começou a dor conflito nos arquivos

2018-11-16 22:03 UTC, closed without merging